# model
model_name_or_path: /root/jt/projects/llama/llama-2-7b-hf

# method
stage: sft
do_train: true
finetuning_type: full
mixture_of_depths: convert

# dataset
dataset: identity,alpaca_gpt4_en
template: llama2
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/llama2-7b-mod/full/sft_full_debug
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
optim: paged_adamw_8bit
learning_rate: 0.0003
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
pure_bf16: true

# eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
