#model
model_name_or_path: /home/yifei/zkli/MoD/LLaMA-Factory/saves/llama2-7b-mod/full/sft_full_debug_0.95epoch2

#method
mixture_of_depths: load

#task
template: fewshot
task: mmlu
split: test
lang: en
n_shot: 5
batch_size: 1